### ISSUE TITLE
Q: tooltips and legend

### ISSUE THREAD

**Issue by bittorf** [mwarning/MeshGraphViewer#10]
is it possible to feed my map.json with explaining words, so that i can see it e.g. by clicking on a node or link or even have a legend explaining the colors?

example:
http://intercity-vpn.de/networks/liszt28/meshrdf/netjson.html

**Comment by mwarning** [comment]
Tooltips and legends are not supported. Maybe someone can provide it or my own need is high enough to implement it myself at some point in the future.
