### ISSUE TITLE
geolocation mode seems not to work

### ISSUE THREAD

**Issue by bittorf** [mwarning/MeshGraphViewer#9]
i just compiled 9add66727f677655e7128c7d0bd1c0916213af92 and started it
with 

```
./graph-viewer --graph map.json
```

i fetch the data with:
```
wget http://intercity-vpn.de/networks/ejbw/meshrdf/map.json
```

the JSON file is not broken. (" cat map.json | jq . && echo OK ")
in topology mode it works as expected, switching
to "S" seems to make all links to disappear, i can only
see some clients...

is the issue in my side?
(tested with firefox+chromium on debian-testing)

**Comment by bittorf** [comment]
my mistake - i encoded everywhere the exact same latlon. sorry for the noise...

**Comment by mwarning** [comment]
Ok. You gave me a very mild heart attack. ;-]
